# Machine Learning

#### Prof. Neylson Crepalde

## Shrinkage

### Ridge Regression

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import RidgeCV
from sklearn.linear_model import LassoCV

from sklearn.metrics import mean_squared_error

In [2]:
bd = pd.read_csv("https://raw.githubusercontent.com/neylsoncrepalde/ML_classes/master/Data/Hitters.csv")
bd.head()

AtBat  Hits  HmRun  Runs  RBI  Walks  Years  CAtBat  CHits  CHmRun  CRuns  \
0    293    66      1    30   29     14      1     293     66       1     30   
1    315    81      7    24   38     39     14    3449    835      69    321   
2    479   130     18    66   72     76      3    1624    457      63    224   
3    496   141     20    65   78     37     11    5628   1575     225    828   
4    321    87     10    39   42     30      2     396    101      12     48   

   CRBI  CWalks League Division  PutOuts  Assists  Errors  Salary NewLeague  
0    29      14      A        E      446       33      20     NaN         A  
1   414     375      N        W      632       43      10   475.0         N  
2   266     263      A        W      880       82      14   480.0         A  
3   838     354      N        E      200       11       3   500.0         N  
4    46      33      N        E      805       40       4    91.5         N

In [3]:
# Preprocessing
bd = pd.get_dummies(bd, drop_first=True)
bd = bd.dropna()
bd.shape

(263, 20)

In [4]:
# Objetivo: predizer o Salário (Salary)
y = bd.Salary
X = bd.drop(columns="Salary")

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.3, random_state=2)

In [6]:
rid = RidgeCV(alphas=np.linspace(0.1, 10), fit_intercept=True, normalize=True, 
              cv=None, # Use eficient LOOCV
             store_cv_values=True)
rid.fit(X_train, y_train)

RidgeCV(alphas=array([ 0.1    ,  0.30204,  0.50408,  0.70612,  0.90816,  1.1102 ,
        1.31224,  1.51429,  1.71633,  1.91837,  2.12041,  2.32245,
        2.52449,  2.72653,  2.92857,  3.13061,  3.33265,  3.53469,
        3.73673,  3.93878,  4.14082,  4.34286,  4.5449 ,  4.74694,
        4.94898,  5.15102...8367,
        8.58571,  8.78776,  8.9898 ,  9.19184,  9.39388,  9.59592,
        9.79796, 10.     ]),
    cv=None, fit_intercept=True, gcv_mode=None, normalize=True,
    scoring=None, store_cv_values=True)

In [7]:
rid.alpha_

0.3020408163265306

In [8]:
rid.coef_

array([ 3.47061317e-02,  1.54808193e+00,  3.55054679e-01,  1.20929609e+00,
        7.24495478e-01,  2.19327133e+00,  8.63872912e-01,  8.75240894e-03,
        6.94922463e-02,  8.37513995e-01,  1.35722267e-01,  1.78099121e-01,
       -1.45796063e-02,  2.48244290e-01, -1.38379082e-01, -7.22165251e-01,
        2.76093487e+01, -9.37106106e+01,  1.64055494e+00])

In [9]:
rid.cv_values_

array([[1.37508262e+02, 5.14172983e+01, 1.77546058e+01, ...,
        9.76492643e+02, 9.91833085e+02, 1.00691930e+03],
       [7.58708019e+04, 6.42397293e+04, 6.14538414e+04, ...,
        9.85667937e+04, 9.91614067e+04, 9.97442819e+04],
       [9.19295300e+03, 1.03256063e+04, 8.66690085e+03, ...,
        1.00261088e+04, 1.03811386e+04, 1.07332984e+04],
       ...,
       [5.87054132e+04, 4.19007684e+04, 3.30542663e+04, ...,
        6.20334040e+03, 6.13416671e+03, 6.06738749e+03],
       [5.22931425e+04, 4.59909583e+04, 3.71917476e+04, ...,
        2.26127598e+04, 2.34803778e+04, 2.43415271e+04],
       [5.02555439e+04, 4.12429747e+04, 3.72895680e+04, ...,
        8.75943772e+04, 8.86315581e+04, 8.96524085e+04]])

In [10]:
yhat_rid = rid.predict(X_test)
np.sqrt(mean_squared_error(y_true=y_test, y_pred=yhat_rid))

397.6960252681132

### LASSO

In [11]:
lasso = LassoCV(n_alphas=100, normalize=True, cv=10)

In [12]:
lasso.fit(X_train, y_train)

LassoCV(alphas=None, copy_X=True, cv=10, eps=0.001, fit_intercept=True,
    max_iter=1000, n_alphas=100, n_jobs=None, normalize=True,
    positive=False, precompute='auto', random_state=None,
    selection='cyclic', tol=0.0001, verbose=False)

In [13]:
lasso.alphas_

array([2.16029875e+01, 2.01470184e+01, 1.87891768e+01, 1.75228492e+01,
       1.63418678e+01, 1.52404806e+01, 1.42133232e+01, 1.32553928e+01,
       1.23620237e+01, 1.15288647e+01, 1.07518578e+01, 1.00272185e+01,
       9.35141757e+00, 8.72116333e+00, 8.13338611e+00, 7.58522311e+00,
       7.07400446e+00, 6.59724023e+00, 6.15260832e+00, 5.73794311e+00,
       5.35122495e+00, 4.99057030e+00, 4.65422256e+00, 4.34054354e+00,
       4.04800543e+00, 3.77518341e+00, 3.52074869e+00, 3.28346201e+00,
       3.06216766e+00, 2.85578781e+00, 2.66331727e+00, 2.48381860e+00,
       2.31641754e+00, 2.16029875e+00, 2.01470184e+00, 1.87891768e+00,
       1.75228492e+00, 1.63418678e+00, 1.52404806e+00, 1.42133232e+00,
       1.32553928e+00, 1.23620237e+00, 1.15288647e+00, 1.07518578e+00,
       1.00272185e+00, 9.35141757e-01, 8.72116333e-01, 8.13338611e-01,
       7.58522311e-01, 7.07400446e-01, 6.59724023e-01, 6.15260832e-01,
       5.73794311e-01, 5.35122495e-01, 4.99057030e-01, 4.65422256e-01,
      

In [14]:
lasso.alpha_

0.24838185972677296

In [15]:
lasso.coef_

array([-1.13571300e+00,  5.52438065e+00, -0.00000000e+00, -0.00000000e+00,
       -2.19353289e-01,  4.38864584e+00, -0.00000000e+00, -0.00000000e+00,
        1.10576487e-01,  1.94998094e+00,  4.28331390e-01,  0.00000000e+00,
       -4.87678084e-01,  3.01438428e-01, -7.79756761e-02,  0.00000000e+00,
        3.44394076e+01, -1.10402526e+02,  0.00000000e+00])

In [16]:
lasso.mse_path_

array([[325620.41275189, 106660.09000354,  99151.91180428,
        207316.49910985, 154358.51031091, 257563.62675298,
        593268.86592311, 178063.97162156, 117090.59958246,
        102667.04871919],
       [308771.18470939, 107662.48230715,  95710.73362744,
        201013.09792446, 147449.35831321, 249183.27028619,
        593268.86592311, 168692.7472367 , 111593.58862089,
         94273.17971544],
       [294683.70769038, 110194.59539817,  92905.03053887,
        195359.70405933, 141416.99882777, 242421.77411341,
        593268.86592311, 160596.28676491, 107275.33311122,
         87218.81561377],
       [282960.03872689, 113945.28407496,  92105.90466468,
        190283.17938417, 136163.0241581 , 236557.58838105,
        573273.72830915, 153604.90123177, 103951.11021572,
         81096.97411007],
       [272996.86984418, 118651.47162864,  92179.40308351,
        185221.77553952, 131405.50913814, 231455.02970611,
        546515.09004355, 147571.24979877, 101462.35944889,
         75

In [17]:
yhat_lasso = lasso.predict(X_test)
np.sqrt(mean_squared_error(y_test, yhat_lasso))

397.51979283736205